class_path: pytorch_lightning.trainer.trainer.Trainer
init_args:
  accelerator: gpu
  devices: 1
  #strategy: ddp
  accumulate_grad_batches: 2
  amp_backend: native
  amp_level: null
  auto_lr_find: False
  auto_scale_batch_size: False
  auto_select_gpus: True
  benchmark: False
  check_val_every_n_epoch: 1
  default_root_dir: null
  deterministic: True
  fast_dev_run: False
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
  #gpus: 1
  #limit_train_batches: 1.0
  #limit_val_batches: 1.0
  #limit_test_batches: 1.0
  #limit_predict_batches: 1.0
  log_every_n_steps: 200
  profiler: null
  overfit_batches: 0
  plugins: null
  precision: 32
  max_epochs: 200
  min_epochs: 100
  #max_steps: -1
  #min_steps: 1000
  #max_time: null
  num_nodes: 1
  num_processes: 1
  num_sanity_val_steps: 10
  #reload_dataloaders_every_n_epochs: 0
  replace_sampler_ddp: True
  sync_batchnorm: False
  #detect_anomaly: False
  #tpu_cores: null
  track_grad_norm: -1
  val_check_interval: .20
  #enable_model_summary: True
  #num_sanity_val_steps: 0
  move_metrics_to_cpu: True
  multiple_trainloader_mode: max_size_cycle
